#!/usr/bin/env bash

set -e

commit_sha=$(git rev-parse HEAD)
commit_msg=$(git log --format=%s -n 1 "$commit_sha")

root=$(git rev-parse --show-toplevel)
$root/bin/faros_event_helper.sh SEND_COMMIT --commit-sha "$commit_sha" --commit-message "$commit_msg"
