#!/usr/bin/env bash

set -e

checkout_type=$3
if [ "$checkout_type" -ne 1 ]; then
    exit 0 # Not a branch checkout
fi

root=$(git rev-parse --show-toplevel)
cur_branches_file="$root/.faros_current_branches"
touch "$cur_branches_file"

branch=$(git rev-parse --abbrev-ref HEAD)
if grep -qE "^$branch$" "$cur_branches_file"; then
    printf "Not new branch\n"
    exit 0
fi

printf "./event.sh run-start %s\n" "$branch"

git branch -l --format='%(refname:short)' >"$cur_branches_file"
